### ISSUE TITLE
Wrong help string in parser

### ISSUE THREAD

**Issue by Serbernari** [facebookresearch/randsent#2]
in randsent.py

parser.add_argument("--se_batch_size", type=int,
help="Batch size for embedding sentences in SentEval (**default 16**).", **default=8**)

**Comment by Serbernari** [comment]
#Network parameters
    parser.add_argument("--**input_dim**", type=int, default=300,
                help="**Output** feature dimensionality (default 300).")

**Comment by douwekiela** [comment]
Fixed by #3  thanks
